steps:
  - id: "build image"
    name: "gcr.io/cloud-builders/docker"
    args: ["build", "-t", "gcr.io/${PROJECT_ID}/${_SERVICE_NAME}:${COMMIT_SHA}", "."]

  - id: "push image"
    name: "gcr.io/cloud-builders/docker"
    args: ["push", "gcr.io/${PROJECT_ID}/${_SERVICE_NAME}:${COMMIT_SHA}"]

  - id: "apply migrations"
    name: "gcr.io/google-appengine/exec-wrapper"
    args:
      [
        "-i",
        "gcr.io/${PROJECT_ID}/${_SERVICE_NAME}:${COMMIT_SHA}",
        "-s",
        "${PROJECT_ID}:${_REGION}:${_CLOUDSQL_INSTANCE}",
        "--",
        "python",
        "manage.py",
        "migrate",
      ]

  - id: "deploy container image to Cloud Run"
    name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    entrypoint: gcloud
    args:
      [
        "run",
        "deploy",
        "${_SERVICE_NAME}",
        "--image",
        "gcr.io/${PROJECT_ID}/${_SERVICE_NAME}:${COMMIT_SHA}",
        "--region",
        "${_REGION}",
      ]

substitutions:
  _CLOUDSQL_INSTANCE: django
  _REGION: asia-northeast1
  _SERVICE_NAME: django-cloudrun-sample

images:
  - "gcr.io/${PROJECT_ID}/${_SERVICE_NAME}:${COMMIT_SHA}"
